version: '3'
services:
  frontend:
    build: ./outpace-front
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./outpace-back
    ports:
      - '8000:8000'
    networks:
      - bridge
networks:
  bridge:
