version: '3'
services:
  frontend:
    build: ./outpace-front
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./outpace-back
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
  db:
    image: postgres
    env_file:
      - .env