name: Build and Push Docker Images

on:  
  push:
    branches:
      - server
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PW }}

    - name: Run backend unit tests
      run: |
        cd back
        python -m pytest tests/

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: ./back
        push: true
        tags: tomademagn/outpace:backend
      env:
        OUTPACE_DB: ${{ secrets.OUTPACE_DB }}
        OUTPACE_HOST: ${{ secrets.OUTPACE_HOST }}
        OUTPACE_PASSWORD: ${{ secrets.OUTPACE_PASSWORD }}
        OUTPACE_PORT: ${{ secrets.OUTPACE_PORT }}
        OUTPACE_USER: ${{ secrets.OUTPACE_USER }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./front
        push: true
        tags: tomademagn/outpace:frontend
      env:
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
        REACT_APP_HOST_URL: ${{ secrets.REACT_APP_HOST_URL }}
        REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
        REACT_APP_ION_DEFAULT_ACCESS_TOKEN: ${{ secrets.REACT_APP_ION_DEFAULT_ACCESS_TOKEN }}
        REACT_APP_WEB_URL: ${{ secrets.REACT_APP_WEB_URL }}
